baseURL = ""
languageCode = "en-us"
title = "Showcase Theme"
Paginate = 1_000
googleAnalytics = ""
theme = "showcase"
disableKinds = [ "taxonomy", "taxonomyTerm", "RSS" ]
pluralizelisttitles = false
themesDir = "themes"
publishDir = "public"

[params]
author = "showcase"
description = "Minimal, one page, theme for showcasing your work"
message = ""
hideAutoMenu = false
paginate = 3
multipage = true
darkMode = true

[[menu.main]]
name = "External"
url = "https://example.com"

[social]
facebook = "https://facebook.com"
twitter = "https://twitter.com"
instagram = "https://instagram.com"
linkedin = "https://linkedin.com"
